import {mkdir,readFile,writeFile} from 'node:fs/promises';
const owner='jccarmenate';
const headers={'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2026-03-10','User-Agent':'night-profile'};
if(process.env.GITHUB_TOKEN) headers.Authorization=`Bearer ${process.env.GITHUB_TOKEN}`;
async function get(path){const r=await fetch(`https://api.github.com${path}`,{headers,signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error(`GitHub ${r.status}: ${path}`);return r.json();}
const profile=await get(`/users/${owner}`);
const repos=[];
for(let page=1;;page++){const batch=await get(`/users/${owner}/repos?per_page=100&page=${page}`);repos.push(...batch);if(batch.length<100)break;}
const incoming=[];
for(let page=1;page<=3;page++){const batch=await get(`/users/${owner}/events/public?per_page=100&page=${page}`);incoming.push(...batch);if(batch.length<100)break;}
const today=new Date().toISOString().slice(0,10), day=86400000, end=Date.parse(today)+day, start=end-30*day;
let old=[];try{old=JSON.parse(await readFile('assets/public-activity.json','utf8')).events;}catch(e){if(e.code!=='ENOENT')throw e;}
const events=new Map(old.map(e=>[e.id,e]));
for(const e of incoming)if(e.public===true&&e.actor?.login?.toLowerCase()===owner&&e.repo?.name!==`${owner}/${owner}`)events.set(e.id,{id:e.id,at:e.created_at,repo:e.repo.name});
const retained=[...events.values()].filter(e=>Date.parse(e.at)>=start&&Date.parse(e.at)<end).sort((a,b)=>b.at.localeCompare(a.at));
const bins=Array.from({length:30},(_,i)=>({date:new Date(start+i*day).toISOString().slice(0,10),count:0}));
for(const e of retained){const index=Math.floor((Date.parse(e.at)-start)/day);bins[index].count++;}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const bg='#080c14',border='#25334d',cyan='#8dddeb',purple='#b794f6',muted='#96a5bb';
function svg(w,h,title,body){return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-labelledby="title"><title id="title">${esc(title)}</title><style>text{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}.pulse{animation:pulse 4s ease-in-out infinite}@keyframes pulse{50%{opacity:.45}}@media(prefers-reduced-motion:reduce){*{animation:none!important}}</style><rect x=".5" y=".5" width="${w-1}" height="${h-1}" rx="9" fill="${bg}" stroke="${border}"/>${body}</svg>\n`;}
await mkdir('assets',{recursive:true});
const out=async(name,text)=>writeFile(`assets/${name}.svg`,text);
await out('profile-bar',svg(1000,48,'jccarmenate / README.md',`<g>${['#ed6a5f','#f4bf50','#61c454'].map((c,i)=>`<circle cx="${23+i*21}" cy="24" r="5" fill="${c}"/>`).join('')}</g><text x="100" y="29" fill="${muted}" font-size="14">jccarmenate <tspan fill="#5e6e88"> / </tspan><tspan fill="#e6edf7">README.md</tspan></text><text x="978" y="29" text-anchor="end" fill="${cyan}" font-size="12">BUILDING WITH CURIOSITY</text>`));
await out('identity-tags',svg(1000,58,'Developer · Open source · AI systems · Compilers · Full-stack', ['Developer','Open Source','AI Systems','Compilers','Full-stack'].map((t,i)=>`<rect x="${16+i*196}" y="12" width="184" height="34" rx="6" fill="#101524" stroke="${i<2?'#493564':'#284b60'}"/><circle class="pulse" cx="${31+i*196}" cy="29" r="4" fill="${i<2?purple:cyan}"/><text x="${45+i*196}" y="34" font-size="13" fill="#e1e5f2">${t}</text>`).join('')));
const max=Math.max(1,...bins.map(x=>x.count));
const bars=bins.map((b,i)=>{const h=Math.max(3,Math.round(b.count/max*80));return `<rect x="${27+i*17}" y="${145-h}" width="11" height="${h}" rx="2" fill="${b.count?(b.count/max>.6?'#8a77f1':'#3e478b'):'#1c2538'}"><title>${b.date}: ${b.count} observed public events</title></rect>`;}).join('');
const activeRepos=new Set(retained.map(e=>e.repo)).size;
const stats=[[profile.public_repos,'Public repositories'],[new Set(repos.map(r=>r.language).filter(Boolean)).size,'Primary languages'],[retained.length,'Observed events'],[activeRepos,'Recently active repos']];
await out('activity',svg(1000,215,`Public activity snapshot ${today}: ${retained.length} observed events over 30 days`, `<text x="24" y="33" fill="${cyan}" font-size="17" font-weight="700">Recent public activity</text><text x="24" y="53" fill="${muted}" font-size="11">30-day snapshot · public events, not contribution totals</text>${bars}<path d="M24 151h511" stroke="${border}"/><text x="24" y="172" fill="${muted}" font-size="11">${bins[0].date}</text><text x="535" y="172" text-anchor="end" fill="${muted}" font-size="11">${today}</text><text x="24" y="195" fill="#697d9c" font-size="10">REST data · daily refresh · profile updates excluded</text>${stats.map(([v,label],i)=>{const x=563+(i%2)*215,y=17+Math.floor(i/2)*91;return `<rect x="${x}" y="${y}" width="202" height="79" rx="7" fill="#0e1420" stroke="${border}"/><path d="M${x+15} ${y+15}v46" stroke="${i%2?purple:cyan}" stroke-width="2"/><text x="${x+30}" y="${y+35}" fill="${i%2?purple:cyan}" font-size="25">${v}</text><text x="${x+30}" y="${y+58}" fill="${muted}" font-size="11">${label}</text>`;}).join('')}`));
const technologies=[['Py','Python','#80b6e5'],['TS','TypeScript','#76baff'],['Rs','Rust','#d7a8c3'],['C','C','#b6a2ff'],['Re','React','#80dbea'],['Pg','PostgreSQL','#93bce5']];
await out('tech-stack',svg(430,375,'Tech stack: Python, TypeScript, Rust, C, React, PostgreSQL',`<text x="22" y="34" fill="${cyan}" font-size="20" font-weight="700">&gt; Tech Stack</text><path d="M20 51h390" stroke="${border}"/>${technologies.map(([symbol,label,color],i)=>{const x=27+(i%3)*133,y=69+Math.floor(i/3)*119;return `<path d="M${x+27} ${y}l27 15v31l-27 15-27-15V${y+15}z" fill="#131c2c" stroke="${color}"/><text x="${x+27}" y="${y+38}" text-anchor="middle" fill="${color}" font-size="24" font-weight="700">${symbol}</text><text x="${x+27}" y="${y+82}" text-anchor="middle" fill="#dce5f3" font-size="12">${label}</text><circle cx="${x+27}" cy="${y+98}" r="3" fill="${color}"/>`;}).join('')}<path d="M20 313h390" stroke="${border}"/><text x="22" y="337" fill="${muted}" font-size="12">FastAPI · LangGraph · LLVM · Prisma</text><text x="22" y="357" fill="${muted}" font-size="12">Docker · Git · GitHub Actions</text>`));
const featured=[['tech-rag-information-retrieval-system','Tech RAG','Search, retrieval and grounded answers','Python / FastAPI / ChromaDB'],['multiagent-code-generator','Multi-agent Code Generator','From a specification to tested applications','Python / LangGraph / Docker'],['hulk-ide','HULK IDE','A compiler and language tooling, from scratch','Rust / LLVM / LSP'],['GuildWork','GuildWork','Role-based project management','TypeScript / React / Prisma']];
for(let i=0;i<featured.length;i++){const [repo,title,desc,stack]=featured[i];if(!repos.some(r=>r.name===repo))throw Error(`Missing public repo: ${repo}`);await out(`project-${i+1}`,svg(530,89,title,`<rect x="14" y="17" width="43" height="43" rx="6" fill="#151d31" stroke="${i%2?purple:cyan}"/><path d="M28 30l-7 8 7 8m15-16 7 8-7 8m-7-21-6 26" fill="none" stroke="${i%2?purple:cyan}" stroke-width="2"/><text x="72" y="28" fill="#e3e9fa" font-size="15" font-weight="700">${title}</text><text x="72" y="49" fill="${muted}" font-size="11">${desc}</text><text x="72" y="70" fill="${i%2?purple:cyan}" font-size="10">${stack}</text>`));}
await out('projects-heading',svg(530,43,'Featured projects',`<text x="15" y="28" fill="${cyan}" font-size="19" font-weight="700">Featured Projects</text>`));
for(const [i,title,subtitle,mark] of [[1,'Portfolio','Selected work & demos','&lt;/&gt;'],[2,'Repositories','Code, experiments & tools','{ }'],[3,'Learning','Current areas of focus','[+]'],[4,'Let’s connect','Email & collaboration','@']])await out(`toolbox-${i}`,svg(245,94,title,`<text x="17" y="40" fill="${i%2?cyan:purple}" font-size="21">${mark}</text><text x="65" y="38" fill="#e3e9fa" font-size="13" font-weight="700">${title}</text><text x="17" y="70" fill="${muted}" font-size="11">${esc(subtitle)}</text>`));
await writeFile('assets/public-activity.json',JSON.stringify({updated:today,events:retained},null,2)+'\n');
console.log(JSON.stringify({updated:today,repositories:profile.public_repos,observedEvents:retained.length,activeRepos}));
